 # Definicion tipos de datos
   es necesario descargar librerias de numpy para poder crear diferentes tipos de datos para operar con numpy.
   
- Arrays
- Matrices

In [13]:
# Importacion de librerias
import numpy as np

Se crean variables nativas de python las que se usan en la creación de variables compatibles con numpy


In [23]:
scalar = 5
array1_v1 = [-5,2,7,1]
array1_v2 = [3,4,-1,0]
array_inside_arrays1 = [1,4]
array_inside_arrays2 = [7,-2]
array_inside_arrays3 = [-2,11]
array_inside_arrays4 = [9,-2]

array_of_arrays = [array_inside_arrays1 , array_inside_arrays2]


## Matriz como una conjunto de arrays. (?)
matriz1 = np.array([array_inside_arrays3,array_inside_arrays4])
matriz2 = np.array(array_of_arrays)


In [24]:
a = np.array(scalar)

In [25]:
v1 = np.array(array1_v1)

In [26]:
m1 = np.array(array_of_arrays)

# Operaciones 
## Vector por escalar


In [27]:
# ExE
res = v1**a
print(res)

[-3125    32 16807     1]


# Producto punto entre dos vectores

In [28]:
v2 = np.array(array1_v2)
res2 = np.dot(v1,v2)
print(res2)

-14


In [29]:
res3 = np.matmul(matriz1,matriz2)
print(res3)
res3

[[ 75 -30]
 [ -5  40]]


array([[ 75, -30],
       [ -5,  40]])

## Cambios de dimensión

### Method that brings the dimensions of a variable
```python
a.shape
```

In [31]:
v1.shape

(4,)

In [32]:
m1.shape

(2, 2)

In [ ]:
a1 = a.reshape(1)
print(a1.shape)

In [ ]:
a2 = a1.reshape(1,1)

In [ ]:
print(a2)

In [ ]:
m0 = m1.reshape(4)
print(m0)